name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        with:
          github_user_name: harshthakkr
          outputs: |
            dist/snake-dark.svg?color_snake=#FF5A1F&color_dots=#1A1A19,#3B2318,#6E3018,#B8441A,#FF5A1F
            dist/snake-light.svg?color_snake=#FF5A1F&color_dots=#ECE9E2,#FFD2BD,#FFA27A,#FF7A45,#FF5A1F
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
